# Generated by Django 3.1.3 on 2020-11-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('celular', models.CharField(max_length=12, unique=True, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=100, unique=True, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Producto')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Precio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Bruto')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Precio Unitario')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='SubTotal')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedidos', verbose_name='Pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.producto', verbose_name='Cliente')),
            ],
        ),
    ]
