# Generated by Django 3.1.3 on 2022-09-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Habitacion')),
                ('estado', models.CharField(choices=[('0', 'Eliminado'), ('1', 'Activo')], default=1, editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reserva', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('EL', 'Eliminado')], default='PE', editable=False, max_length=2)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('YAPE', 'YAPE'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='PE', editable=False, max_length=15)),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('documento_identidad_cliente', models.CharField(max_length=15, verbose_name='Documento Identidad')),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Monto Pagar')),
            ],
        ),
        migrations.CreateModel(
            name='FechaReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.habitacion', verbose_name='Habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
