# Generated by Django 3.1.3 on 2022-09-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechareserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fecha_reservas', to='hotel.habitacion', verbose_name='Habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('EL', 'Eliminado')], default='PE', editable=False, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('YAPE', 'YAPE'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='PE', editable=False, max_length=15, verbose_name='Metodo de pago'),
        ),
    ]
