# Generated by Django 3.1.3 on 2022-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220908_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('EL', 'Eliminado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('YAPE', 'YAPE'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='PE', max_length=15, verbose_name='Metodo de pago'),
        ),
    ]
