# Generated by Django 3.1.3 on 2022-09-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20220908_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechareserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.reserva', verbose_name='Reserva'),
        ),
    ]
